import { readFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { PATHS } from './paths.js';
import { ensureLocalInkosProject } from './inkos-runner.js';
import { PUBLISHER_LLM_CONFIG_FILE } from './llm-secret-store.js';
import { hardenPrivateFile, writePrivateFile } from './private-file.js';
import { normalizeLlmBaseUrl } from './llm-endpoint.js';

const CONFIG_FILE = PUBLISHER_LLM_CONFIG_FILE;
export const DEFAULT_LLM_MODEL = 'gpt-5.6-terra';

// InkOS config is project-local: <repo>/book/inkos.json.
// We also keep a UI mirror in data/inkos-config.json. Do not write ~/.inkos/.env;
// this app runs the bundled InkOS CLI inside the project-local book workspace.

function ensureDataDir() {
  const dir = dirname(CONFIG_FILE);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function configDataError(file, cause) {
  const err = new Error(`InkOS 配置文件损坏，请先恢复 ${file}: ${cause.message}`);
  err.code = 'CONFIG_DATA_INVALID';
  err.statusCode = 503;
  err.cause = cause;
  return err;
}

export function assertInkosProjectConfig(config) {
  if (!config || typeof config !== 'object' || Array.isArray(config)) {
    throw new Error('配置根节点必须是对象');
  }
  if (config.llm != null && (typeof config.llm !== 'object' || Array.isArray(config.llm))) {
    throw new Error('llm 必须是对象');
  }
  if (config.modelOverrides != null && (typeof config.modelOverrides !== 'object' || Array.isArray(config.modelOverrides))) {
    throw new Error('modelOverrides 必须是对象');
  }
  return config;
}

export function getInkosConfig() {
  ensureDataDir();
  if (!existsSync(CONFIG_FILE)) {
    return { provider: 'openai', model: DEFAULT_LLM_MODEL, reviewModel: DEFAULT_LLM_MODEL, reviewBaseUrl: '', reviewApiKey: '', baseUrl: '', apiKey: '', apiFormat: 'chat', stream: false, temperature: null, maxTokens: null, thinkingBudget: 0 };
  }
  try {
    hardenPrivateFile(CONFIG_FILE);
    const parsed = JSON.parse(readFileSync(CONFIG_FILE, 'utf-8'));
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('配置根节点必须是对象');
    return { provider: 'openai', model: DEFAULT_LLM_MODEL, thinkingBudget: 0, stream: false, reviewModel: DEFAULT_LLM_MODEL, reviewBaseUrl: '', reviewApiKey: '', apiFormat: 'chat', ...parsed, provider: 'openai', apiFormat: 'chat' };
  } catch (err) {
    throw configDataError(CONFIG_FILE, err);
  }
}


export function getReviewModelConfig(stored = getInkosConfig(), effective = getEffectiveInkosConfig()) {
  const baseUrl = stored.reviewBaseUrl || stored.baseUrl || effective.baseUrl || process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1';
  return {
    model: stored.reviewModel || process.env.PUBLISHER_REVIEW_MODEL || process.env.PUBLISHER_SIMPLE_CREATE_MODEL || DEFAULT_LLM_MODEL,
    baseUrl: normalizeLlmBaseUrl(baseUrl),
    apiKey: stored.reviewApiKey || stored.apiKey || effective.apiKey || process.env.OPENAI_API_KEY || '',
  };
}

export function saveInkosConfig(cfg) {
  ensureDataDir();
  writePrivateFile(CONFIG_FILE, JSON.stringify({ ...cfg, provider: 'openai', apiFormat: 'chat' }, null, 2));
}

// Read the currently-effective project-local InkOS LLM config.
export function getEffectiveInkosConfig() {
  const result = { provider: '', model: '', baseUrl: '', apiFormat: '', stream: null, temperature: null, thinkingBudget: 0, apiKey: '', source: 'unknown' };
  // Project-level inkos.json
  const configPath = join(PATHS.BOOKS_DIR, 'inkos.json');
  if (!existsSync(configPath)) return result;
  try {
    hardenPrivateFile(configPath);
    const j = assertInkosProjectConfig(JSON.parse(readFileSync(configPath, 'utf-8')));
    const llm = j.llm || {};
    result.provider = llm.provider || result.provider;
    result.model = llm.model || result.model;
    result.baseUrl = llm.baseUrl || result.baseUrl;
    result.apiFormat = llm.apiFormat || result.apiFormat;
    result.stream = llm.stream ?? result.stream;
    result.temperature = llm.temperature ?? result.temperature;
    result.thinkingBudget = llm.thinkingBudget ?? 0;
    result.apiKey = llm.apiKey || result.apiKey;
    result.source = 'project';
  } catch (err) {
    throw configDataError(configPath, err);
  }
  return result;
}


function envLine(key, value) {
  const text = String(value ?? '');
  const escaped = text.replace(/\\/g, '\\\\').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/"/g, '\\"');
  return `${key}="${escaped}"`;
}

function writeProjectEnvFromLlm(llm) {
  ensureLocalInkosProject();
  const envPath = join(PATHS.BOOKS_DIR, '.env');
  const lines = [
    '# Auto-generated by chapter-publisher. Keeps bundled InkOS isolated from ~/.inkos/.env.',
  ];
  if (llm.provider) lines.push(envLine('INKOS_LLM_PROVIDER', llm.provider));
  if (llm.service) lines.push(envLine('INKOS_LLM_SERVICE', llm.service));
  if (llm.baseUrl) lines.push(envLine('INKOS_LLM_BASE_URL', llm.baseUrl));
  if (llm.model) lines.push(envLine('INKOS_LLM_MODEL', llm.model));
  if (llm.apiFormat) lines.push(envLine('INKOS_LLM_API_FORMAT', llm.apiFormat));
  if (llm.stream !== undefined) lines.push(envLine('INKOS_LLM_STREAM', String(Boolean(llm.stream))));
  lines.push(envLine('INKOS_LLM_THINKING_BUDGET', String(llm.thinkingBudget ?? 0)));
  if (llm.temperature !== undefined && llm.temperature !== null) lines.push(envLine('INKOS_LLM_TEMPERATURE', llm.temperature));
  // Secrets are injected into child processes from the private publisher store.
  // Rewriting this file also removes any legacy INKOS_LLM_API_KEY entry.
  writePrivateFile(envPath, lines.join('\n') + '\n');
}

function readProjectConfig() {
  ensureLocalInkosProject();
  const configPath = join(PATHS.BOOKS_DIR, 'inkos.json');
  if (!existsSync(configPath)) {
    return {
      name: 'chapter-publisher-books',
      version: '0.1.0',
      language: 'zh',
      llm: {},
      notify: [],
    };
  }
  try {
    return assertInkosProjectConfig(JSON.parse(readFileSync(configPath, 'utf-8')));
  } catch (err) {
    throw configDataError(configPath, err);
  }
}

function writeProjectConfig(config) {
  ensureLocalInkosProject();
  const configPath = join(PATHS.BOOKS_DIR, 'inkos.json');
  writePrivateFile(configPath, JSON.stringify(config, null, 2) + '\n');
}

function asNumberOrNull(value) {
  if (value === undefined || value === null || value === '') return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

// Apply non-secret settings to project-local book/inkos.json. The bundled CLI
// rejects llm.apiKey, so secrets stay in the private publisher store and are
// injected into each child process by inkos-runner.
export async function applyInkosConfig(input) {
  const legacyEffective = getEffectiveInkosConfig();
  const cfg = {
    ...input,
    provider: 'openai',
    apiFormat: 'chat',
    apiKey: input.apiKey || legacyEffective.apiKey || '',
  };
  cfg.baseUrl = normalizeLlmBaseUrl(cfg.baseUrl, { allowEmpty: true });
  cfg.reviewBaseUrl = normalizeLlmBaseUrl(cfg.reviewBaseUrl, { allowEmpty: true });

  const config = readProjectConfig();
  const llm = { ...(config.llm || {}) };
  const applied = [];

  // Child processes receive secrets from the private publisher config store.
  // Remove the legacy project copy so inkos.json and book/.env remain shareable.
  delete llm.apiKey;
  llm.configSource = 'env';
  applied.push('llm.configSource');
  // Do not enable provider reasoning/thinking mode. InkOS only flips
  // piModel.reasoning on when thinkingBudget > 0, so keep it pinned to 0.
  llm.thinkingBudget = 0;
  applied.push('llm.thinkingBudget');
  if (llm.extra && typeof llm.extra === 'object') {
    delete llm.extra.reasoning;
    delete llm.extra.reasoning_effort;
    delete llm.extra.thinking;
    delete llm.extra.enable_thinking;
  }

  llm.provider = 'openai';
  applied.push('llm.provider');
  if (cfg.model) { llm.model = cfg.model; applied.push('llm.model'); }
  if (cfg.baseUrl) { llm.baseUrl = cfg.baseUrl; applied.push('llm.baseUrl'); }
  if (cfg.apiKey) applied.push('publisher.apiKey');
  llm.apiFormat = 'chat';
  applied.push('llm.apiFormat');
  if (cfg.reviewModel) {
    const overrides = { ...(config.modelOverrides || {}) };
    const reviewBaseUrl = cfg.reviewBaseUrl || cfg.baseUrl || llm.baseUrl || '';
    const reviewOverride = (cfg.reviewBaseUrl || cfg.reviewApiKey)
      ? {
          model: cfg.reviewModel,
          ...(reviewBaseUrl ? { baseUrl: reviewBaseUrl } : {}),
          provider: cfg.provider || llm.provider || 'openai',
          ...(cfg.reviewApiKey ? { apiKeyEnv: 'PUBLISHER_REVIEW_API_KEY' } : {}),
          stream: false,
        }
      : cfg.reviewModel;
    overrides.architect = reviewOverride;
    overrides['foundation-reviewer'] = reviewOverride;
    config.modelOverrides = overrides;
    applied.push('modelOverrides.architect');
    applied.push('modelOverrides.foundation-reviewer');
  }
  if (cfg.stream !== undefined && cfg.stream !== null) { llm.stream = Boolean(cfg.stream); applied.push('llm.stream'); }
  else if (llm.stream === undefined) { llm.stream = false; applied.push('llm.stream'); }
  const temperature = asNumberOrNull(cfg.temperature);
  if (temperature !== null) { llm.temperature = temperature; applied.push('llm.temperature'); }
  const maxTokens = asNumberOrNull(cfg.maxTokens);
  if (maxTokens !== null) { llm.maxTokens = maxTokens; applied.push('llm.maxTokens'); }

  config.llm = llm;
  writeProjectConfig(config);
  writeProjectEnvFromLlm(llm);
  saveInkosConfig(cfg);
  applied.push('book/.env');
  return { applied: applied.length, fields: applied, errors: [] };
}
